module.exports.erc1967 = require('./erc1967')
module.exports.gateway = require('./gateway')
module.exports.gatewayV1 = require('./gateway')
module.exports.erc20 = require('./erc20')
module.exports.erc721 = require('./erc721')
module.exports.state = require('./state')
module.exports.zvengersNFT = require('./zvengersNFT')
